### ISSUE TITLE
USB Power Latch (Models < v2.1)

### ISSUE THREAD

**Issue by bschulz1701** [NorthernWidget-Skunkworks/Project-Margay#18]
### Issue:
When USB power is connected while the battery is simultaneously connected, there is a small additional power draw due to voltage mismatches (~160uA @ 4.5v). This draw results in a latching of the USB power switch, such that when the USB is removed, the FTDI draws power parasitically from the battery (~400uA @ 4.5v), this problem persists even in sleep mode and power down. 

### Workaround:
If the USB is desired to be connected while battery is also connected (to check battery voltage, system status, etc), it is recommended to minimize this time simply to reduce draw on the battery. Then, once the USB is removed, make sure to **power cycle the battery**, this will fix the latching problem. 

#### Updates:
The latching problem has been fixed on models >= `v2.1`, so no power cycle is required. However, the small current draw due to voltage mismatch is still present, so it is still recommended to reduce the time both are connected, simply to preserve the battery charge.

**Comment by awickert** [comment]
Closing per @bschulz1701: This has been resolved on newer versions, so the general problem has been solved. This will stay as an archive for those concerned about power draw in prior versions.
