### ISSUE TITLE
Reverse Polarity with USB (Model v0.0)

### ISSUE THREAD

**Issue by bschulz1701** [NorthernWidget-Skunkworks/Project-Margay#19]
### Issue:
When USB power is applied **and** the battery is reverse polarized **destructive heating can occur**. 

This issue occurs only when (reverse polarity) battery power is applied, followed by USB power. When this occurs, power is dissipated across `Q2` (the reverse polarity protection diode), causing significant heating. 

#### Testing: 
The following tests were performed in order to characterize the performance of the reverse current protection 
**Test 1:**
USB power applied, **then** reverse polarity battery voltage applied
V<sub>Bat</sub> = 4.5v (power supply)
V<sub>USB</sub> = 5v (power supply)
T<sub>Ambient</sub> = 25&deg;C

| Time [s] | I<sub>Bat</sub> [mA] | T<sub>Q2</sub> [&deg;C] | 
| --------  | -------------------------- | ------------------------------  | 
| 0 | 16.3 | 25 |
| 15 | 16.3 | 30 |
| 30 | 16.3 | 32 |
| 120 | 16.3 | 35* | 

*Stabilized temp

Note: These results are the same for all power cycling conditions for Model > v0.0

**Test 2:**
Reverse battery power applied, **then** USB voltage applied
V<sub>Bat</sub> = 4.5v (power supply)
V<sub>USB</sub> = 5v (power supply)
T<sub>Ambient</sub> = 25&deg;C

| Time [s] | I<sub>Bat</sub> [mA] | T<sub>Q2</sub> [&deg;C] | 
| --------  | -------------------------- | ------------------------------  | 
| 0 | 16.3 | 25 |
| 5 | 110 | 35 |
| 15 | 126 | 67 |
| 30 | 130 | 85 | 
| 60 | 130 | 100 | 

### Workaround:
For these older models, it is recommended to connect the battery power with **USB disconnected**, then verify by the presence of status lights that the logger is properly powered. Once this is verified, it is then safe to connect USB in parallel as usual.

**Comment by awickert** [comment]
v0.0 is long superceded; closing per @bschulz1701 and leaving this as a warning for anyone using our few pieces of earliest hardware. (Currently just us and two collaborators.)
